### ISSUE TITLE
Downloaded videos are not being saved in photos album

### ISSUE THREAD

**Issue by DarthGigi** [BandarHL/BHTikTok#27]
Downloading tiktoks (without watermarks) in BHTikTok is broken.

BHTikTok says that the video has been downloaded but it's not being  saved to the photos app.

Downloading images works fine.

**Comment by jaydenss** [comment]
Also having the same issue, but downloading with watermark works

**Comment by xinjilaoyang** [comment]
bhtiktok is not running properly now, please fix it, thank you
