### ISSUE TITLE
Long press menu of the org. app is not reachable

### ISSUE THREAD

**Issue by gototheskinny** [BandarHL/BHTikTok#9]
This should be reachable:
![image](https://github.com/BandarHL/BHTikTok/assets/51786709/20d92f71-c338-47e6-810e-b9da1f937b5b)
With this tweak long press does this: ![image](https://github.com/BandarHL/BHTikTok/assets/51786709/ec1f5854-3562-4554-bf7f-837a97026e75)

**Comment by dayanch96** [comment]
So you want ‘Open TikTok’s menu’ option there?

**Comment by gototheskinny** [comment]
> So you want ‘Open TikTok’s menu’ option there?

Yeah, or it could be the opposite the tiktok menu could have a bhtiktok menu option? Either way it's fine for me.

**Comment by mbs0ft** [comment]
Yep, can confirm that bug
